### PR TITLE
Fix pytest-cov warning after upgrading to 6.0.0

### PR DESCRIPTION
**Pull request by ezio-melotti**
This is an attempt to fix the following warning seen in #405:
```
     warnings.warn(CentralCovContextWarning(message), stacklevel=1)
 pytest_cov.CentralCovContextWarning: Detected dynamic_context=test_function
 in coverage configuration. This is unnecessary as this plugin provides the
 more complete --cov-context option.
```

### CODE REVIEW

**Comment by ezio-melotti** [comment]
The warning seems to be fixed, but 3.8 is failing since it's not longer supported by `pytest-cov` `6.0.0`.

**Comment by hugovk** [comment]
3.8 is EOL, let's drop it: https://github.com/python/blurb_it/pull/407

**Comment by ezio-melotti** [comment]
I can merge this into #405.
Is there someone that can enable the "Update branch" button on PRs so that we can merge `main` and update the PR with #407?

**Comment by ezio-melotti** [comment]
The "Automatically delete branch after merging" should be enabled too :upside_down_face:

**Pull request merged**
